package net.defiancecoding.bot.util.highscores;

public class Members {

    public static String[] members = {
            "CV Cursed CC",
            "Vpcalais",
            "G A M 3",
            "I O W N F2P",
            "Me is iKing",
            "PharoahRiper",
            "P1NPO1NT",
            "QuickRedFoxx",
            "PattyMelts",
            "St4Tu3 TTV",
            "JMSKLMN",
            "Windy City",
            "EUI64FFFE",
            "The unvaXXed",
            "Bambis mum",
            "Mikeal H",
            "ImNotShadii",
            "_Kruk jr",
            "u0h",
            "JimmyNotHere",
            "baff water",
            "xIceHotx",
            "Tikishiyo",
            "cobbahh",
            "CoIntelPro",
            "Beasywitit",
            "noodle head",
            "Big Rays",
            "RockyAspen",
            "Pepsi Nation",
            "4KT Youngboy",
            "El Igor",
            "Sol Kiske",
            "Slipmat",
            "Ovi D Sama",
            "PANZUH",
            "Puunyo",
            "that person",
            "Dr Hass",
            "2eggzN_hanky",
            "Star Jedai",
            "The Godsend",
            "Nerdy Virgin",
            "GeneDangus92",
            "Jeffsman92",
            "121 Void Boy",
            "T zilla94",
            "Aeluun",
            "Vannca",
            "Doriyah Rus",
            "Jayreals",
            "Armadyll",
            "Youngblood4u",
            "fiighter1360",
            "ComradePugs",
            "Dooobz",
            "Capt Murphy",
            "M0ND4YZ",
            "P for Perc",
            "Mr Duvel",
            "CleanChatka",
            "C00kiepk",
            "Dreadnough77",
            "l3L4CK M4G1C",
            "JooneBuice",
            "Pearce Buie",
            "Lord Rhat",
            "Shiat ali",
            "Arbury Main",
            "Nihang Fauj",
            "Jave",
            "Craw Wurm",
            "Good Memes",
            "Homers1515",
            "TheDickButt",
            "PuckFutinn",
            "SW00PY B0I",
            "Jemmz",
            "UnholyNuns",
            "Not iKing",
            "c ar lo",
            "Giga Fart",
            "CV iKing",
            "StarlitMoon",
            "dxxphouse",
            "Redwolf5893",
            "MJteddy",
            "4erb",
            "purebalance1",
            "pep pep nips",
            "Robe47",
            "IITIIatt",
            "sad boy simp",
            "Chode4Mom",
            "DoinkerDan",
            "Mic Fiend",
            "Sir Gregador",
            "Cyber n Bug",
            "BA heal",
            "Silentrisk",
            "Engineer710",
            "4nnn",
            "Gp pig",
            "Milk Dudz",
            "iKing Def",
            "Loki vs Kang",
            "CV Tank",
            "WhatTheRug",
            "Sir Danefurt",
            "BigMaji",
            "Deathplaug4",
            "Eternalol",
            "Mr Coolrpant",
            "XxDusty",
            "hmu say wsup",
            "IrisHelin",
            "YoinkyMcdood",
            "MrLoganT",
            "Handl3d_You",
            "RobinhoodJj",
            "Moth Effect",
            "iKing Tank",
            "Darsee MC",
            "Timothie",
            "420 Dank",
            "M R NaCl",
            "shifty shafe",
            "Desperadofar",
            "Caloenn",
            "MobilesOnly",
            "GengR lll",
            "Kiddie Range",
            "DAGNOMECHlLD",
            "CoreysWrld",
            "ISing4Gp",
            "Burnt Kiwi",
            "Zappyboi",
            "Cupfutbol1",
            "Vipin",
            "Un5toppa4ble",
            "MilwaukeeRed",
            "KushNap",
            "JustVibinMan",
            "Gte9",
            "Fat Chally",
            "reecegambles",
            "Crypto OG",
            "PeskyPuma",
            "Henry Nest",
            "Eolas",
            "Tesco",
            "IM Drunken J",
            "Rattty",
            "MoistShrimp",
            "Vuurvlieg",
            "on sedatives",
            "Ziminiar",
            "Sunny Varnes",
            "Rusticles16",
            "Dark Leader",
            "StrokeMyWhip",
            "Save Kyiv",
            "Shagserker",
            "MedicTF3",
            "Arbury Pure",
            "Zwarte Fluit",
            "Mq3",
            "tunadickrick",
            "Stockish",
            "Stumpy Ronin",
            "HussDied",
            "Ffa SpareGp",
            "iFederali",
            "ShuperPee",
            "RoccoTheDawg",
            "LinksSword",
            "TheFinders",
            "CV Burner",
            "SirJax a Lot",
            "a dumb goth",
            "Zerito",
            "bigbadboone",
            "mp3 warriorr",
            "Toncehas",
            "234M",
            "Dante Verdan",
            "MrSourMilk",
            "ets_jit",
            "SirSplsh0lot",
            "XxDerek",
            "TheBigEyedea",
            "Langfoo69",
            "lil Stik",
            "SpiltMyYak",
            "annnn den",
            "iKing Death",
            "No Dice Sry",
            "Retro TD",
            "Justavip",
            "Indications",
            "Yaks Milk",
            "Anchors Down",
            "Lil Sk3t",
            "ChadMcNasty",
            "Z e n y t e",
            "A Piano Man",
            "Xhunterx24",
            "Amelia70",
            "Adult Cat",
            "BarreFlirre",
            "Two Brews",
            "Pray to Fly",
            "Packing One"
    };
}
